services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:+Inw7PtmjKhb7k2YG/T7DePq7nEnM8OK76hcVrbJ66I=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql10.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql10780141
      - key: DB_USERNAME
        value: sql10780141
      - key: DB_PASSWORD
        value: zXWUymgz3k